### PR TITLE
[1] Support for Translation task 

### PR DESCRIPTION
**Pull request by Mehrad0711**
Main changes:

- Added support for translation task and related models: Marian, MBART, T5
- Some general cleanups on paraphrasing code
- A new sentence generation method by masking tokens in the input sentence and using BART/ MBART to denoise the sentence. Can be used in single/ multi language settings and observed better results with MBART.

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
I eyeballed this, but I'm going to let @s-jse do a full review because this is mostly code that touches the paraphrase part of genienlp.

**Comment by Mehrad0711** [comment]
Sounds good. 
The 3 Signature mismatch warnings are irrelevant as the code in 'transformer_utils.py' is adapted from huggingface.

**Comment by s-jse** [comment]
In terms of functionality, things look good. Please just

- [x]  Add a test for masked paraphrasing
- [x] Move helper functions that are specific to the translation task out of `run_generation.py`

**Comment by Mehrad0711** [comment]
ok, done and done. Any other comments? Otherwise, it's good to go.

**Comment by s-jse** [comment]
I think you can merge now.

**Pull request merged**
