### PR TITLE
Fix exporting models

### PR DESCRIPTION
**Pull request by gcampax**
Initialize the numericalizer correctly so we don't try to load files
that don't exist

### CODE REVIEW

**Review by s-jse — COMMENTED** [review]
I guess this works, but I don't understand why we need to manually load and save the `numericalizer`.
Also, what is this export doing that `cp -r` cannot do?

**Comment by gcampax** [comment]
The goal of export is to remove all the files that we don't need at inference time, such as the optimizer files and the intermediate checkpoints. There are two ways to do that: copy everything and skip files that we know we don't need, or copy only the files we know we need. Loading and saving the numericalizer copies all the numericalizer files (which we know we need), so it accomplishes the latter.

**Comment by s-jse** [comment]
> 
> 
> The goal of export is to remove all the files that we don't need at inference time, such as the optimizer files and the intermediate checkpoints. There are two ways to do that: copy everything and skip files that we know we don't need, or copy only the files we know we need. Loading and saving the numericalizer copies all the numericalizer files (which we know we need), so it accomplishes the latter.

`GenieModel.from_pretrained()` already loads the numericalizer, why do we need to load it again separately?

**Comment by gcampax** [comment]
Oh good catch, I meant to remove that line.

**Review by s-jse — APPROVED** [review]

**Pull request merged**
