### PR TITLE
Wip/entity resolution

### PR DESCRIPTION
**Pull request by s-jse**
NOT ready, use for code review only.

### CODE REVIEW

**Comment by gcampax** [comment]
You should have let @Mehrad0711 open the PR, because now you can't review it :(

Also, a couple things that MUST happen before this PR is mergeable:
- remove the JSON DB files
- replace the DB implementation with something not backed by a file
- remove the "split" argument everywhere
- revert the changes to server.py (because otherwise we need to sync changes to genie-toolkit for absolutely no benefit)
- remove the oracle
- rebase and squash the patches into a reviewable state
- ensure that arguments have correct defaults, such that (1) training with the current flags, unmodified, has no changes, and (2) all previously trained models continue to evaluate exactly in the same way

**Comment by gcampax** [comment]
If you copy code, you must add the appropriate copyright notices. Also, don't copy code.

**Comment by gcampax** [comment]
If you didn't tie the oracle to the split, and made it a direct "entity-linker=[oracle | naive | bootleg]" flag, you wouldn't need a "no_oracle" flag, and you woudn't have double negations all over the place. Negated flags are bad.

**Comment by Mehrad0711** [comment]
> If you copy code, you must add the appropriate copyright notices. Also, don't copy code.

The code in "transformer_utils.py" is adopted from huggingface and changed to support processing of encoder-decoder cross-attention. I will merge and move up all the licenses to the beginning of the file.

**Comment by Mehrad0711** [comment]
> You should have let @Mehrad0711 open the PR, because now you can't review it :(
> 
> Also, a couple things that MUST happen before this PR is mergeable:
> 
> * remove the JSON DB files
> * replace the DB implementation with something not backed by a file
> * remove the "split" argument everywhere
> * revert the changes to server.py (because otherwise we need to sync changes to genie-toolkit for absolutely no benefit)
> * remove the oracle
> * rebase and squash the patches into a reviewable state
> * ensure that arguments have correct defaults, such that (1) training with the current flags, unmodified, has no changes, and (2) all previously trained models continue to evaluate exactly in the same way

I created a new branch "wip/entity_resolution_2" addressing these comments, cleaning up, refactoring, and removing options that did not improve the results. I'm gonna close this one now...

**Pull request closed without merging**
